export interface Meal {
  id: number
  nameAr: string
  nameEn: string
  image: string
  nutritionPer100g: {
    calories: number
    fat: number
    sugar: number
    sodium: number
  }
  healthImpactAr: string
  healthImpactEn: string
  alternativeAr: string
  alternativeEn: string
  colorIndex: "red" | "yellow" | "green"
}

export const mealsDatabase: Meal[] = [
  {
    id: 1,
    nameAr: "كبسة دجاج",
    nameEn: "Chicken Kabsa",
    image: "/chicken-kabsa-saudi-rice-dish.jpg",
    nutritionPer100g: { calories: 175, fat: 7.5, sugar: 1.2, sodium: 240 },
    healthImpactAr: "قد ترفع السعرات المتراكمة خاصة إن كانت مطبوخة بزيوت أو مرق عالي الملح",
    healthImpactEn: "May increase accumulated calories especially if cooked with oils or high-salt broth",
    alternativeAr: "نفس الطبق مع تقليل الزيت والملح وزيادة السلطة الجانبية",
    alternativeEn: "Same dish with reduced oil and salt, plus more side salad",
    colorIndex: "yellow",
  },
  {
    id: 2,
    nameAr: "كبسة لحم",
    nameEn: "Lamb Kabsa",
    image: "/lamb-kabsa-saudi-rice-dish.jpg",
    nutritionPer100g: { calories: 210, fat: 11.5, sugar: 1.0, sodium: 250 },
    healthImpactAr: "الدهون المشبعة المتكررة قد ترفع الكوليسترول وتزيد دهون البطن",
    healthImpactEn: "Repeated saturated fats may raise cholesterol and increase belly fat",
    alternativeAr: "تقليل كمية اللحم أو استبدال نصفها بلحم أقل دهوناً",
    alternativeEn: "Reduce meat quantity or replace half with leaner meat",
    colorIndex: "red",
  },
  {
    id: 3,
    nameAr: "مظبي دجاج",
    nameEn: "Chicken Madhbi",
    image: "/chicken-madhbi-grilled-saudi-dish.jpg",
    nutritionPer100g: { calories: 165, fat: 6, sugar: 0.5, sodium: 220 },
    healthImpactAr: "خيار أخف من الأطباق البريانية لكنه يتأثر حسب كمية الملح والدهن",
    healthImpactEn: "Lighter option than biryani dishes but depends on salt and fat amount",
    alternativeAr: "نفس الطبق مع إزالة الجلد وتقليل الملح",
    alternativeEn: "Same dish with skin removed and reduced salt",
    colorIndex: "yellow",
  },
  {
    id: 4,
    nameAr: "مندي لحم",
    nameEn: "Lamb Mandi",
    image: "/lamb-mandi-yemeni-rice-dish.jpg",
    nutritionPer100g: { calories: 205, fat: 10.5, sugar: 1.0, sodium: 230 },
    healthImpactAr: "المتابعة اليومية قد تزيد الدهون الحشوية",
    healthImpactEn: "Daily consumption may increase visceral fat",
    alternativeAr: "استبداله بدجاج مندي أو تقليل كمية الأرز",
    alternativeEn: "Replace with chicken mandi or reduce rice quantity",
    colorIndex: "red",
  },
  {
    id: 5,
    nameAr: "سليق",
    nameEn: "Saleeg",
    image: "/photo_5_2025-10-24_16-44-39.jpg",
    nutritionPer100g: { calories: 170, fat: 6, sugar: 1.5, sodium: 250 },
    healthImpactAr: "يُعتبر السليق وجبة خفيفة نسبيًا، لكن الإفراط في استخدام الزبدة أو المرق المملّح قد يرفع الصوديوم والدهون.",
    healthImpactEn: "Salt-rich broth raises sodium with repetition",
    alternativeAr: "استبدل الزبدة بكمية قليلة من الزيت النباتي",
    alternativeEn: "Reduce salty broth and replace with lighter broth",
    colorIndex: "yellow",
  },
  {
  id: 6,
  nameAr: "مرقوق",
  nameEn: "Marqooq",
  image: "/photo_6_2025-10-24_16-44-39.jpg",
  nutritionPer100g: { calories: 150, fat: 4, sugar: 2, sodium: 220 },
  healthImpactAr: "وجبة مشبعة ومغذية، لكن الطحين الأبيض المكرر قد يرفع سكر الدم مع التكرار.",
  healthImpactEn: "A hearty and nutritious meal, but refined flour may raise blood sugar with frequent consumption.",
  alternativeAr: "استخدام دقيق حبوب كاملة وتقليل الزيت.",
  alternativeEn: "Use whole-grain flour and reduce oil.",
  colorIndex: "yellow",
},
{
  id: 7,
  nameAr: "جريش",
  nameEn: "Jareesh",
  image: "/photo_8_2025-10-24_16-44-39.jpg",
  nutritionPer100g: { calories: 145, fat: 3, sugar: 0.6, sodium: 170 },
  healthImpactAr: "خيار ممتاز للشبع ببطء وتحكم أفضل بسكر الدم مقارنة بالأرز.",
  healthImpactEn: "Excellent for slow satiety and better blood sugar control compared to rice.",
  alternativeAr: "تقليل السمن أو استبداله بزيت نباتي خفيف.",
  alternativeEn: "Reduce ghee or replace with light vegetable oil.",
  colorIndex: "green",
},
{
  id: 8,
  nameAr: "هريس",
  nameEn: "Harees",
  image: "/photo_7_2025-10-24_16-44-39.jpg",
  nutritionPer100g: { calories: 140, fat: 2.5, sugar: 0.5, sodium: 190 },
  healthImpactAr: "مشبع ومعتدل، مفيد للتحكم بالوزن عند طهيه بدون سمن.",
  healthImpactEn: "Filling and moderate; helps weight control if cooked without ghee.",
  alternativeAr: "تقديمه بدون سمن أو بكمية قليلة جدًا.",
  alternativeEn: "Serve without ghee or use minimal amount.",
  colorIndex: "green",
},
{
  id: 9,
  nameAr: "ثريد",
  nameEn: "Thareed",
  image: "/photo_9_2025-10-24_16-44-39.jpg",
  nutritionPer100g: { calories: 155, fat: 5, sugar: 2, sodium: 250 },
  healthImpactAr: "يحتوي على خضار ولحم مفيد، لكن المرق المالح المتكرر قد يرفع الضغط.",
  healthImpactEn: "Contains vegetables and meat, but salty broth may raise blood pressure.",
  alternativeAr: "استخدام خبز حبوب كاملة ومرق أقل ملحًا.",
  alternativeEn: "Use whole-grain bread and less salty broth.",
  colorIndex: "yellow",
},
{
  id: 10,
  nameAr: "روبيان مقلي",
  nameEn: "Fried Shrimp",
  image: "/rob.png",
  nutritionPer100g: { calories: 240, fat: 12, sugar: 0.5, sodium: 360 },
  healthImpactAr: "الروبيان المقلي غني بالبروتين لكنه يحتوي على دهون وزيت امتصته القلي، مما يرفع السعرات والصوديوم.",
  healthImpactEn: "Fried shrimp is rich in protein but contains absorbed oils and fats, increasing calories and sodium.",
  alternativeAr: "روبيان مشوي أو في القلاية الهوائية لتقليل الدهون.",
  alternativeEn: "Grilled or air-fried shrimp to reduce fat content.",
  colorIndex: "red",
},

 {
  id: 11,
  nameAr: "صيادية سمك",
  nameEn: "Fish Sayadiyah",
  image: "/syad.png",
  nutritionPer100g: { calories: 160, fat: 5, sugar: 1, sodium: 260 },
  healthImpactAr: "وجبة بحرية متوازنة غنية بالبروتين وأوميغا 3، لكن قلي السمك أو إضافة الصلصة المالحة قد ترفع الصوديوم.",
  healthImpactEn: "A balanced seafood meal rich in protein and omega-3, but frying or salty sauce may increase sodium levels.",
  alternativeAr: "استخدام سمك مشوي أو مطهو بالبخار مع تقليل كمية الزيت والملح.",
  alternativeEn: "Use grilled or steamed fish with reduced oil and salt.",
  colorIndex: "green",
},
{
  id: 12,
  nameAr: "كبيبة",
  nameEn: "Kibbeh",
  image: "/KOBAYBA72022952.gif",
  nutritionPer100g: { calories: 220, fat: 10, sugar: 0.8, sodium: 320 },
  healthImpactAr: "وجبة غنية بالبروتين من اللحم والبرغل، لكن القلي يرفع الدهون والسعرات بشكل ملحوظ.",
  healthImpactEn: "Rich in protein from meat and bulgur, but deep frying increases fat and calorie content.",
  alternativeAr: "كبيبة مشوية أو مطهوة في الفرن لتقليل الدهون.",
  alternativeEn: "Grilled or oven-baked kibbeh to reduce fat.",
  colorIndex: "yellow",
},
{
  id: 13,
  nameAr: "مطبق لحم",
  nameEn: "Meat Mutabbaq",
  image: "/photo_13_2025-10-24_16-44-39.jpg",
  nutritionPer100g: { calories: 250, fat: 13, sugar: 1.8, sodium: 380 },
  healthImpactAr: "دهون مشبعة عالية مع القلي المتكرر، وقد ترفع الكوليسترول عند الإكثار.",
  healthImpactEn: "High saturated fats with repeated frying; may raise cholesterol when consumed often.",
  alternativeAr: "تحضيره في القلاية الهوائية أو استبدال جزء من الحشوة بخضار.",
  alternativeEn: "Air-fry or replace part of the filling with vegetables.",
  colorIndex: "red",
},
{
  id: 14,
  nameAr: "مطبق خضار",
  nameEn: "Veggie Mutabbaq",
  image: "/photo_14_2025-10-24_16-44-39.jpg",
  nutritionPer100g: { calories: 210, fat: 8.5, sugar: 2, sodium: 300 },
  healthImpactAr: "خيار أخف من مطبق اللحم، لكنه يبقى عالي السعرات عند القلي.",
  healthImpactEn: "Lighter than the meat version but still high in calories when fried.",
  alternativeAr: "خبزه في الفرن أو القلاية الهوائية لتقليل الزيت.",
  alternativeEn: "Bake or air-fry instead of deep frying to reduce oil.",
  colorIndex: "yellow",
},
{
  id: 15,
  nameAr: "سمبوسة جبن",
  nameEn: "Cheese Sambusa",
  image: "/photo_15_2025-10-24_16-44-39.jpg",
  nutritionPer100g: { calories: 290, fat: 17, sugar: 1, sodium: 420 },
  healthImpactAr: "القلي والجبن معًا يرفعان الدهون والصوديوم بشكل كبير عند التكرار.",
  healthImpactEn: "Frying and cheese together increase fats and sodium significantly with repetition.",
  alternativeAr: "سمبوسة بالفرن أو بحشوة سبانخ قليلة الدسم.",
  alternativeEn: "Oven-baked sambusa or with a light spinach filling.",
  colorIndex: "red",
},
{
  id: 16,
  nameAr: "سمبوسة لحم",
  nameEn: "Meat Sambusa",
  image: "/photo_16_2025-10-24_16-44-39.jpg",
  nutritionPer100g: { calories: 280, fat: 15, sugar: 1, sodium: 410 },
  healthImpactAr: "نفس مخاطر الأطعمة المقلية — ترفع السعرات والدهون المشبعة عند الإفراط.",
  healthImpactEn: "Same risks of fried foods — increases calories and saturated fats when overconsumed.",
  alternativeAr: "تحضيرها في الفرن أو القلاية الهوائية.",
  alternativeEn: "Prepare in the oven or air fryer instead of deep frying.",
  colorIndex: "red",
},
{
  id: 17,
  nameAr: "خبز تميس",
  nameEn: "Tamees Bread",
  image: "/photo_28_2025-10-24_16-44-39.jpg",
  nutritionPer100g: { calories: 285, fat: 2.5, sugar: 2, sodium: 500 },
  healthImpactAr: "يُعد مشبعًا وغنيًا بالكربوهيدرات، لكن الصوديوم العالي في بعض أنواعه قد يرفع الضغط.",
  healthImpactEn: "Filling and rich in carbs, but high sodium in some types may raise blood pressure.",
  alternativeAr: "اختيار تميس حبوب كاملة أو قليل الملح.",
  alternativeEn: "Choose whole-grain or low-sodium tamees bread.",
  colorIndex: "yellow",
},
{
  id: 18,
  nameAr: "مشروب الشمندر",
  nameEn: "Beetroot Juice",
  image: "/chmandar.jpg", 
  nutritionPer100g: { calories: 45, fat: 0.2, sugar: 9, sodium: 50 },
  healthImpactAr: "يساعد على تحسين تدفق الدم والطاقة بسبب محتواه من النترات الطبيعية، لكن الإكثار منه قد يسبب انخفاض الضغط.",
  healthImpactEn: "Helps improve blood flow and energy due to natural nitrates, but excessive intake may lower blood pressure.",
  alternativeAr: "شربه باعتدال أو مزجه مع عصير برتقال طبيعي.",
  alternativeEn: "Drink in moderation or mix with natural orange juice.",
  colorIndex: "green",
},
{
  id: 19,
  nameAr: "خبز عربي",
  nameEn: "Arabic Pita",
  image: "/kobz.jpg.avif",
  nutritionPer100g: { calories: 270, fat: 1, sugar: 1.5, sodium: 320 },
  healthImpactAr: "خبز بسيط وخفيف، لكنه مصنوع من دقيق أبيض مكرر قد يرفع سكر الدم مع التكرار.",
  healthImpactEn: "Light and simple bread, but made from refined white flour that may raise blood sugar with frequent use.",
  alternativeAr: "خبز عربي من دقيق الحبوب الكاملة أو الشوفان.",
  alternativeEn: "Whole-grain or oat-based Arabic bread.",
  colorIndex: "yellow",
},
{
  id: 20,
  nameAr: "حمص",
  nameEn: "Hummus",
  image: "/photo_30_2025-10-24_16-44-39.jpg",
  nutritionPer100g: { calories: 165, fat: 9.5, sugar: 0.3, sodium: 250 },
  healthImpactAr: "غني بالبروتين النباتي والألياف، لكن الإضافات الزيتية قد ترفع السعرات.",
  healthImpactEn: "Rich in plant protein and fiber, but extra oil may increase calorie content.",
  alternativeAr: "حمص بزيت أقل أو بطحينة خفيفة.",
  alternativeEn: "Hummus with less oil or light tahini.",
  colorIndex: "green",
},

{
  id: 21,
  nameAr: "فلافل",
  nameEn: "Falafel",
  image: "/photo_31_2025-10-24_16-44-39.jpg",
  nutritionPer100g: { calories: 330, fat: 17, sugar: 0.5, sodium: 290 },
  healthImpactAr: "غنية بالبروتين النباتي والألياف، لكن القلي المتكرر يرفع الدهون والسعرات.",
  healthImpactEn: "Rich in plant protein and fiber, but repeated frying raises fats and calories.",
  alternativeAr: "فلافل مشوية أو في القلاية الهوائية لتقليل الزيت.",
  alternativeEn: "Grilled or air-fried falafel to reduce oil.",
  colorIndex: "yellow",
},
{
  id: 22,
  nameAr: "تبولة",
  nameEn: "Tabbouleh",
  image: "/photo_32_2025-10-24_16-44-39.jpg",
  nutritionPer100g: { calories: 120, fat: 6, sugar: 2.2, sodium: 180 },
  healthImpactAr: "غنية بالألياف والفيتامينات وتساعد على الشبع والتحكم بالشهية.",
  healthImpactEn: "Rich in fiber and vitamins, helps promote fullness and appetite control.",
  alternativeAr: "خيار صحي بالفعل لا يحتاج بديل.",
  alternativeEn: "Already a healthy choice; no replacement needed.",
  colorIndex: "green",
},
{
  id: 23,
  nameAr: "سلطة فتوش",
  nameEn: "Fattoush",
  image: "/photo_33_2025-10-24_16-44-39.jpg",
  nutritionPer100g: { calories: 110, fat: 5, sugar: 2, sodium: 200 },
  healthImpactAr: "سلطة خفيفة وصحية، لكن الخبز المقلي المستخدم قد يرفع السعرات.",
  healthImpactEn: "Light and healthy salad, but the fried bread can increase calories.",
  alternativeAr: "استخدام خبز محمص بدل المقلي.",
  alternativeEn: "Use toasted bread instead of fried.",
  colorIndex: "green",
},
{
  id: 24,
  nameAr: "كبدة مشوية",
  nameEn: "Grilled Liver",
  image: "/kbdah msh.png",
  nutritionPer100g: { calories: 175, fat: 6, sugar: 0, sodium: 85 },
  healthImpactAr: "مصدر ممتاز للحديد والبروتين، مناسبة عند الاعتدال لكن لا يُنصح بتناولها يوميًا بسبب الكوليسترول.",
  healthImpactEn: "Excellent source of iron and protein; suitable in moderation but not daily due to cholesterol content.",
  alternativeAr: "شويها بملح خفيف وبدون زيت إضافي.",
  alternativeEn: "Grill with light salt and no added oil.",
  colorIndex: "green",
},
{
  id: 25,
  nameAr: "كبدة",
  nameEn: "Liver",
  image: "/photo_17_2025-10-24_16-44-39.jpg",
  nutritionPer100g: { calories: 190, fat: 8, sugar: 0, sodium: 140 },
  healthImpactAr: "وجبة غنية بالحديد والبروتين، جيدة للطاقة والدم إذا طُهيت بدون زيت زائد.",
  healthImpactEn: "Rich in iron and protein; good for energy and blood if cooked with minimal oil.",
  alternativeAr: "كبدة مشوية أو مطهية بزيت نباتي خفيف.",
  alternativeEn: "Grilled liver or cooked with light vegetable oil.",
  colorIndex: "green",
},
{
  id: 26,
  nameAr: "كفتة",
  nameEn: "Kofta",
  image: "/kofth.png",
  nutritionPer100g: { calories: 250, fat: 14, sugar: 0, sodium: 410 },
  healthImpactAr: "مصدر جيد للبروتين لكن محتواها من الدهون يعتمد على نوع اللحم المستخدم.",
  healthImpactEn: "Good source of protein, but fat level depends on the meat type used.",
  alternativeAr: "استخدام لحم قليل الدهن أو دجاج بدلاً من اللحم الأحمر.",
  alternativeEn: "Use lean meat or chicken instead of red meat.",
  colorIndex: "yellow",
},
{
  id: 27,
  nameAr: "هامور مشوي",
  nameEn: "Grilled Hamour",
  image: "/photo_18_2025-10-24_16-44-39.jpg",
  nutritionPer100g: { calories: 140, fat: 3.5, sugar: 0, sodium: 170 },
  healthImpactAr: "بروتين بحري خفيف غني بالأوميغا 3 ويفيد القلب.",
  healthImpactEn: "Light seafood protein rich in omega-3, beneficial for heart health.",
  alternativeAr: "لا حاجة — خيار صحي وممتاز.",
  alternativeEn: "No need — already a healthy option.",
  colorIndex: "green",
},
{
  id: 28,
  nameAr: "دجاج على الفحم",
  nameEn: "Charcoal Chicken",
  image: "/akPOxk6ENRX0Jt6VMb17f6TPKkkn7rBulGLAtld0.webp",
  nutritionPer100g: { calories: 165, fat: 6, sugar: 0, sodium: 210 },
  healthImpactAr: "خيار صحي غني بالبروتين، يفضل إزالة الجلد لتقليل الدهون.",
  healthImpactEn: "Healthy protein source; remove skin to reduce fat content.",
  alternativeAr: "تناوله مع خضار أو سلطة بدل الخبز.",
  alternativeEn: "Serve with vegetables or salad instead of bread.",
  colorIndex: "green",
},
{
  id: 29,
  nameAr: "شاورما دجاج",
  nameEn: "Chicken Shawarma",
  image: "/3058141066323-11-02accf102caaa970ce65d217b9ae9a8e9a57caa67c.jpg",
  nutritionPer100g: { calories: 420, fat: 17, sugar: 5, sodium: 900 },
  healthImpactAr: "لذيذة لكنها عالية بالصوديوم والزيوت، مما يرفع الضغط والدهون مع الوقت.",
  healthImpactEn: "Tasty but high in sodium and oils, which may raise blood pressure and fats over time.",
  alternativeAr: "شاورما مشوية بصلصة خفيفة وملح أقل.",
  alternativeEn: "Grilled shawarma with light sauce and less salt.",
  colorIndex: "red",
},
{
  id: 30,
  nameAr: "شاورما لحم",
  nameEn: "Beef Shawarma",
  image: "/meet.jpg",
  nutritionPer100g: { calories: 470, fat: 22, sugar: 5, sodium: 950 },
  healthImpactAr: "دهون وصوديوم أعلى من شاورما الدجاج، وقد ترفع الكوليسترول عند الإكثار.",
  healthImpactEn: "Higher in fat and sodium than chicken shawarma; may raise cholesterol with frequent consumption.",
  alternativeAr: "استبدالها بشاورما دجاج مشوية أو لحم قليل الدهن.",
  alternativeEn: "Replace with grilled chicken shawarma or lean beef.",
  colorIndex: "red",
},

  {
  id: 31,
  nameAr: "أرز أبيض مطبوخ",
  nameEn: "Cooked White Rice",
  image: "/rz.jpg",
  nutritionPer100g: { calories: 130, fat: 0.3, sugar: 0.1, sodium: 1 },
  healthImpactAr: "مصدر طاقة سريع وسهل الهضم، لكن تناوله بكثرة بدون توازن مع البروتين أو الخضار قد يرفع السعرات والسكر في الدم.",
  healthImpactEn: "Quick energy source and easy to digest, but eating large amounts without balance from protein or vegetables can raise calories and blood sugar.",
  alternativeAr: "نصف الكمية مع خضار أو بروتين مثل الدجاج أو السمك.",
  alternativeEn: "Eat half the portion with vegetables or protein such as chicken or fish.",
  colorIndex: "yellow",
},
{
  id: 32,
  nameAr: "عدس مطبوخ",
  nameEn: "Cooked Lentils",
  image: "/ads.jpg",
  nutritionPer100g: { calories: 116, fat: 0.4, sugar: 1, sodium: 4 },
  healthImpactAr: "وجبة غنية بالبروتين النباتي والألياف، تساعد على الشبع وتحافظ على استقرار سكر الدم.",
  healthImpactEn: "Rich in plant protein and fiber; promotes fullness and helps stabilize blood sugar.",
  alternativeAr: "تحضيره بزيت زيتون خفيف أو مع خضار متنوعة.",
  alternativeEn: "Cook with light olive oil or mix with vegetables for added nutrition.",
  colorIndex: "green",
},

  {
  id: 33,
  nameAr: "فول مدمس",
  nameEn: "Foul Medames",
  image: "/photo_22_2025-10-24_16-44-39.jpg",
  nutritionPer100g: { calories: 110, fat: 0.5, sugar: 0.6, sodium: 30 },
  healthImpactAr: "وجبة غنية بالبروتين النباتي والألياف، تساعد على الشبع وتنظيم سكر الدم.",
  healthImpactEn: "Rich in plant protein and fiber; helps with fullness and stabilizing blood sugar levels.",
  alternativeAr: "تقديمه بزيت الزيتون أو مع خضار طازجة بدل السمن.",
  alternativeEn: "Serve with olive oil or fresh vegetables instead of ghee.",
  colorIndex: "green",
},
{
  id: 34,
  nameAr: "لبنة",
  nameEn: "Labneh",
  image: "/photo_23_2025-10-24_16-44-39.jpg",
  nutritionPer100g: { calories: 170, fat: 10, sugar: 4, sodium: 250 },
  healthImpactAr: "مصدر ممتاز للكالسيوم والبروتين، لكن الأنواع كاملة الدسم قد تحتوي دهون مشبعة عالية.",
  healthImpactEn: "Excellent source of calcium and protein, but full-fat versions may contain high saturated fats.",
  alternativeAr: "اختيار لبنة قليلة الدسم أو تناول كمية صغيرة مع زيت زيتون خفيف.",
  alternativeEn: "Choose low-fat labneh or small portions drizzled with olive oil.",
  colorIndex: "yellow",
},
{
  id: 35,
  nameAr: "زبادي سادة",
  nameEn: "Plain Yogurt",
  image: "/photo_24_2025-10-24_16-44-39.jpg",
  nutritionPer100g: { calories: 60, fat: 3.8, sugar: 4.7, sodium: 36 },
  healthImpactAr: "يدعم الهضم وصحة الأمعاء، ويُعتبر خيارًا ممتازًا قبل النوم أو مع الوجبات.",
  healthImpactEn: "Supports digestion and gut health; an excellent option before sleep or with meals.",
  alternativeAr: "يمكن إضافة فواكه طبيعية بدل السكر.",
  alternativeEn: "Add natural fruits instead of sugar.",
  colorIndex: "green",
},
{
  id: 36,
  nameAr: "لبن",
  nameEn: "Laban",
  image: "/lban .jpg",
  nutritionPer100g: { calories: 40, fat: 1.5, sugar: 3.5, sodium: 150 },
  healthImpactAr: "يساعد على الترطيب بعد الوجبات أو أثناء الحر، ويُفضل تقليل الأنواع عالية الصوديوم.",
  healthImpactEn: "Helps hydration after meals or in hot weather; best to avoid high-sodium brands.",
  alternativeAr: "تحضيره منزليًا بملح أقل أو بدون إضافات.",
  alternativeEn: "Make at home with less salt and no additives.",
  colorIndex: "green",
},
{
  id: 37,
  nameAr: "قهوة عربية",
  nameEn: "Arabic Coffee",
  image: "/2b41138b-224e-47c9-af40-878d6e676363-1000x1000-2fYAFkGspYzX1zv2QMcpkAi8AyhxUagLCtqzEEQD.webp",
  nutritionPer100g: { calories: 0, fat: 0, sugar: 0, sodium: 0 },
  healthImpactAr: "مشروب آمن ومنخفض السعرات، يُفضل الاعتدال وتجنب الإكثار من التمر المرافق لها.",
  healthImpactEn: "A safe, low-calorie drink; enjoy in moderation and limit the number of dates served with it.",
  alternativeAr: "قهوة بدون هيل أو بدون سكر لمن يعاني من القولون.",
  alternativeEn: "Coffee without cardamom or sugar for sensitive digestion.",
  colorIndex: "green",
},
{
  id: 38,
  nameAr: "شاي كرك بسكر",
  nameEn: "Karak Tea (with Sugar)",
  image: "/krk.jpeg",
  nutritionPer100g: { calories: 65, fat: 2.5, sugar: 9, sodium: 40 },
  healthImpactAr: "مشروب دافئ ومنعش لكنه يحتوي على سكر مرتفع، مما قد يرفع الوزن وسكر الدم عند الإكثار.",
  healthImpactEn: "A warm and refreshing drink but high in sugar, which may increase weight and blood sugar when overconsumed.",
  alternativeAr: "تحضيره بدون سكر أو باستخدام محليات طبيعية مثل العسل بكمية صغيرة.",
  alternativeEn: "Prepare without sugar or use a small amount of natural honey instead.",
  colorIndex: "yellow",
},
{
  id: 39,
  nameAr: "تمر خلاص",
  nameEn: "Khalas Dates",
  image: "/tmr.webp",
  nutritionPer100g: { calories: 277, fat: 0.2, sugar: 66, sodium: 1 },
  healthImpactAr: "غني بالطاقة والعناصر الغذائية، لكنه مرتفع جدًا بالسكريات لذلك يُنصح بتناوله باعتدال.",
  healthImpactEn: "Rich in energy and nutrients but very high in sugar; best consumed in moderation.",
  alternativeAr: "تناول 2 إلى 3 تمرات بدل الكمية الكبيرة.",
  alternativeEn: "Limit to 2–3 dates instead of a large handful.",
  colorIndex: "red",
},
{
  id: 40,
  nameAr: "تمر سكري",
  nameEn: "Sukkari Dates",
  image: "/TMR SK.png",
  nutritionPer100g: { calories: 300, fat: 0.5, sugar: 72, sodium: 2 },
  healthImpactAr: "من أكثر أنواع التمر حلاوة، يرفع سكر الدم بسرعة خاصة عند تناوله بكثرة.",
  healthImpactEn: "One of the sweetest types of dates; raises blood sugar quickly when consumed in large amounts.",
  alternativeAr: "اختيار تمر أقل حلاوة مثل الخلاص أو الصقعي.",
  alternativeEn: "Choose less sweet varieties such as Khalas or Sagai.",
  colorIndex: "red",
},

{
  id: 41,
  nameAr: "معصوب",
  nameEn: "Masoub",
  image: "/masob.jpg",
  nutritionPer100g: { calories: 210, fat: 6, sugar: 20, sodium: 120 },
  healthImpactAr: "وجبة شعبية غنية بالألياف والطاقة، لكن إضافة العسل والسكر يرفع السعرات والسكريات بشكل كبير.",
  healthImpactEn: "Traditional dish rich in fiber and energy, but added honey and sugar greatly increase calories and sugar.",
  alternativeAr: "تحضيره بدون عسل أو مع موز فقط بدون سكر إضافي.",
  alternativeEn: "Prepare without honey or with banana only, no added sugar.",
  colorIndex: "yellow",
},
{
  id: 42,
  nameAr: "مقشوش",
  nameEn: "Maqshoush",
  image: "/makshosh.jpg",
  nutritionPer100g: { calories: 260, fat: 8, sugar: 15, sodium: 140 },
  healthImpactAr: "وجبة تراثية دسمة تحتوي على طحين وسمن وعسل، تمد بالطاقة لكنها عالية الدهون والسكر.",
  healthImpactEn: "Traditional dish made with flour, ghee, and honey — energizing but high in fat and sugar.",
  alternativeAr: "تحضيرها بسمن أقل واستخدام عسل طبيعي بكميات بسيطة.",
  alternativeEn: "Prepare with less ghee and use small amounts of natural honey.",
  colorIndex: "red",
},
{
  id: 43,
  nameAr: "لقيمات",
  nameEn: "Luqaimat",
  image: "/logamat.jpg",
  nutritionPer100g: { calories: 330, fat: 14, sugar: 23, sodium: 270 },
  healthImpactAr: "حلوى مقلية غنية بالدهون والسكريات، تسبب ارتفاع سريع بالسعرات والدهون المتراكمة.",
  healthImpactEn: "Deep-fried dessert rich in fat and sugar, rapidly increases calorie and fat accumulation.",
  alternativeAr: "خبزها في القلاية الهوائية واستخدام دبس تمر طبيعي خفيف.",
  alternativeEn: "Air-fry and use light date syrup instead of heavy sugar syrup.",
  colorIndex: "red",
},
{
  id: 44,
  nameAr: "كنافة",
  nameEn: "Kunafa",
  image: "/knafh.jpg",
  nutritionPer100g: { calories: 420, fat: 20, sugar: 37, sodium: 320 },
  healthImpactAr: "من أكثر الحلويات دسامة وغنى بالسكر والدهون، تناولها المتكرر يرفع الوزن والكوليسترول.",
  healthImpactEn: "One of the richest desserts in sugar and fat; frequent intake raises weight and cholesterol.",
  alternativeAr: "تحضيرها بسكر أقل أو بدون قطر.",
  alternativeEn: "Prepare with less sugar or without syrup.",
  colorIndex: "red",
},
{
  id: 45,
  nameAr: "بسبوسة",
  nameEn: "Basbousa",
  image: "/bsbosah.jpg.avif",
  nutritionPer100g: { calories: 370, fat: 17, sugar: 28, sodium: 260 },
  healthImpactAr: "تحتوي على دقيق وسكر ودهون، مما يجعلها مرتفعة السعرات وتزيد الوزن مع الوقت.",
  healthImpactEn: "Contains flour, sugar, and fat, making it calorie-dense and contributing to gradual weight gain.",
  alternativeAr: "تحضيرها بدقيق شوفان أو جوز الهند وتقليل القطر.",
  alternativeEn: "Prepare with oat or coconut flour and reduce syrup amount.",
  colorIndex: "red",
},
{
  id: 46,
  nameAr: "مهلبية",
  nameEn: "Muhallabia",
  image: "/mohalbeh.jpg",
  nutritionPer100g: { calories: 130, fat: 3, sugar: 16, sodium: 50 },
  healthImpactAr: "تحلية خفيفة نسبيًا، مناسبة إن كانت بسكر معتدل وحليب قليل الدسم.",
  healthImpactEn: "A relatively light dessert; fine when made with moderate sugar and low-fat milk.",
  alternativeAr: "تحضيرها بسكر أقل أو مع محليات طبيعية مثل العسل.",
  alternativeEn: "Make with less sugar or natural sweeteners like honey.",
  colorIndex: "yellow",
},
{
  id: 47,
  nameAr: "عصير مانجو",
  nameEn: "Mango Juice",
  image: "/mango.jpg",
  nutritionPer100g: { calories: 60, fat: 0.2, sugar: 14, sodium: 5 },
  healthImpactAr: "غني بفيتامين C وA، لكن سكر العصير يرفع سكر الدم سريعًا مقارنة بالفاكهة الكاملة.",
  healthImpactEn: "Rich in vitamins C and A, but juice sugar raises blood sugar faster than eating the fruit.",
  alternativeAr: "أكل المانجو كاملة بدل العصير.",
  alternativeEn: "Eat whole mango instead of drinking the juice.",
  colorIndex: "yellow",
},
{
  id: 48,
  nameAr: "عصير رمان",
  nameEn: "Pomegranate Juice",
  image: "/roman .jpg",
  nutritionPer100g: { calories: 54, fat: 0.3, sugar: 13, sodium: 1 },
  healthImpactAr: "مفيد كمضاد أكسدة ويدعم القلب، لكن السكر في العصير التجاري قد يكون مرتفعًا.",
  healthImpactEn: "Rich in antioxidants and supports heart health, but commercial juices may contain high sugar.",
  alternativeAr: "تناول حبوب الرمان الطازجة بدل العصير.",
  alternativeEn: "Eat fresh pomegranate seeds instead of juice.",
  colorIndex: "yellow",
},
{
  id: 49,
  nameAr: "ماء",
  nameEn: "Water",
  image: "/ma.jpg",
  nutritionPer100g: { calories: 0, fat: 0, sugar: 0, sodium: 0 },
  healthImpactAr: "الأفضل دائمًا للترطيب وتنظيم وظائف الجسم، لا بديل عنه في نظام صحي متوازن.",
  healthImpactEn: "Always the best choice for hydration and regulating body functions; irreplaceable in a healthy lifestyle.",
  alternativeAr: "—",
  alternativeEn: "—",
  colorIndex: "green",
},
{
  id: 50,
  nameAr: "مشروب الزنجبيل بالعسل",
  nameEn: "Ginger Honey Drink",
  image: "/tbl_articles_article_27018_722195c5eab-b5ce-4e8c-bac0-30a767ec7093.jpg", 
  nutritionPer100g: { calories: 25, fat: 0, sugar: 6, sodium: 5 },
  healthImpactAr: "مشروب دافئ يعزز المناعة وينشط الدورة الدموية، مفيد في الشتاء لكن يُفضل عدم الإكثار بسبب السكر.",
  healthImpactEn: "A warm drink that boosts immunity and blood circulation, great in winter but should be consumed in moderation due to sugar content.",
  alternativeAr: "تحضيره بعسل طبيعي أقل أو بدون سكر مضاف.",
  alternativeEn: "Prepare with less honey or no added sugar.",
  colorIndex: "green",
},

]
