export interface Meal {
  id: number
  nameAr: string
  nameEn: string
  image: string
  nutritionPer100g: {
    calories: number
    fat: number
    sugar: number
    sodium: number
  }
  healthImpactAr: string
  healthImpactEn: string
  alternativeAr: string
  alternativeEn: string
  colorIndex: "red" | "yellow" | "green"
}

export const mealsDatabase: Meal[] = [
  {
    id: 1,
    nameAr: "كبسة دجاج",
    nameEn: "Chicken Kabsa",
    image: "/chicken-kabsa-saudi-rice-dish.jpg",
    nutritionPer100g: { calories: 175, fat: 7.5, sugar: 1.2, sodium: 240 },
    healthImpactAr: "قد ترفع السعرات المتراكمة خاصة إن كانت مطبوخة بزيوت أو مرق عالي الملح",
    healthImpactEn: "May increase accumulated calories especially if cooked with oils or high-salt broth",
    alternativeAr: "نفس الطبق مع تقليل الزيت والملح وزيادة السلطة الجانبية",
    alternativeEn: "Same dish with reduced oil and salt, plus more side salad",
    colorIndex: "yellow",
  },
  {
    id: 2,
    nameAr: "كبسة لحم",
    nameEn: "Lamb Kabsa",
    image: "/lamb-kabsa-saudi-rice-dish.jpg",
    nutritionPer100g: { calories: 210, fat: 11.5, sugar: 1.0, sodium: 250 },
    healthImpactAr: "الدهون المشبعة المتكررة قد ترفع الكوليسترول وتزيد دهون البطن",
    healthImpactEn: "Repeated saturated fats may raise cholesterol and increase belly fat",
    alternativeAr: "تقليل كمية اللحم أو استبدال نصفها بلحم أقل دهوناً",
    alternativeEn: "Reduce meat quantity or replace half with leaner meat",
    colorIndex: "red",
  },
  {
    id: 3,
    nameAr: "مظبي دجاج",
    nameEn: "Chicken Madhbi",
    image: "/chicken-madhbi-grilled-saudi-dish.jpg",
    nutritionPer100g: { calories: 165, fat: 6, sugar: 0.5, sodium: 220 },
    healthImpactAr: "خيار أخف من الأطباق البريانية لكنه يتأثر حسب كمية الملح والدهن",
    healthImpactEn: "Lighter option than biryani dishes but depends on salt and fat amount",
    alternativeAr: "نفس الطبق مع إزالة الجلد وتقليل الملح",
    alternativeEn: "Same dish with skin removed and reduced salt",
    colorIndex: "yellow",
  },
  {
    id: 4,
    nameAr: "مندي لحم",
    nameEn: "Lamb Mandi",
    image: "/lamb-mandi-yemeni-rice-dish.jpg",
    nutritionPer100g: { calories: 205, fat: 10.5, sugar: 1.0, sodium: 230 },
    healthImpactAr: "المتابعة اليومية قد تزيد الدهون الحشوية",
    healthImpactEn: "Daily consumption may increase visceral fat",
    alternativeAr: "استبداله بدجاج مندي أو تقليل كمية الأرز",
    alternativeEn: "Replace with chicken mandi or reduce rice quantity",
    colorIndex: "red",
  },
  {
    id: 5,
    nameAr: "سليق",
    nameEn: "Saleeg",
    image: "/saleeg-saudi-white-rice-milk-dish.jpg",
    nutritionPer100g: { calories: 170, fat: 6, sugar: 1.5, sodium: 250 },
    healthImpactAr: "مرقة غنية بالملح ترفع الصوديوم مع التكرار",
    healthImpactEn: "Salt-rich broth raises sodium with repetition",
    alternativeAr: "تقليل المرقة المالحة واستبدالها بمرق أخف",
    alternativeEn: "Reduce salty broth and replace with lighter broth",
    colorIndex: "yellow",
  },
  {
    id: 6,
    nameAr: "مرقوق",
    nameEn: "Marqooq",
    image: "/marqooq-saudi-stew-with-dough.jpg",
    nutritionPer100g: { calories: 150, fat: 4, sugar: 2, sodium: 220 },
    healthImpactAr: "طبخة مشبعة لكن الطحين المكرر قد يرفع السكر مع التكرار",
    healthImpactEn: "Filling dish but refined flour may raise blood sugar with repetition",
    alternativeAr: "استخدام دقيق حبوب كاملة",
    alternativeEn: "Use whole grain flour",
    colorIndex: "yellow",
  },
  {
    id: 7,
    nameAr: "جريش",
    nameEn: "Jareesh",
    image: "/jareesh-saudi-crushed-wheat-porridge.jpg",
    nutritionPer100g: { calories: 145, fat: 3.2, sugar: 0.6, sodium: 180 },
    healthImpactAr: "يُعد خيارًا أفضل من الأرز للشبع على المدى الطويل",
    healthImpactEn: "Better option than rice for long-term satiety",
    alternativeAr: "تقليل السمن واستبداله بزيت خفيف",
    alternativeEn: "Reduce ghee and replace with light oil",
    colorIndex: "green",
  },
  {
    id: 8,
    nameAr: "هريس",
    nameEn: "Harees",
    image: "/harees-saudi-wheat-meat-porridge.jpg",
    nutritionPer100g: { calories: 140, fat: 2.5, sugar: 0.5, sodium: 190 },
    healthImpactAr: "مشبع ومعتدل، جيد للتحكم بالوزن إن لم يضاف سمن",
    healthImpactEn: "Filling and moderate, good for weight control if no ghee added",
    alternativeAr: "تقديمه بدون سمن أو بكمية قليلة جدًا",
    alternativeEn: "Serve without ghee or with very little amount",
    colorIndex: "green",
  },
  {
    id: 9,
    nameAr: "ثريد",
    nameEn: "Thareed",
    image: "/thareed-saudi-bread-stew.jpg",
    nutritionPer100g: { calories: 155, fat: 5, sugar: 2, sodium: 260 },
    healthImpactAr: "الملح المتكرر في المرق قد يرفع الضغط",
    healthImpactEn: "Repeated salt in broth may raise blood pressure",
    alternativeAr: "استخدام خبز حبوب كاملة ومرق أقل ملحًا",
    alternativeEn: "Use whole grain bread and less salty broth",
    colorIndex: "yellow",
  },
  {
    id: 10,
    nameAr: "مكبوس روبيان",
    nameEn: "Shrimp Machboos",
    image: "/shrimp-machboos-gulf-rice-dish.jpg",
    nutritionPer100g: { calories: 150, fat: 4, sugar: 1, sodium: 310 },
    healthImpactAr: "الروبيان عالي الصوديوم بطبيعته، الزيادة قد ترفع ضغط الدم",
    healthImpactEn: "Shrimp is naturally high in sodium, excess may raise blood pressure",
    alternativeAr: "تقليل الملح والاعتماد على البهارات الخفيفة",
    alternativeEn: "Reduce salt and rely on light spices",
    colorIndex: "yellow",
  },
  {
    id: 11,
    nameAr: "مكبوس سمك",
    nameEn: "Fish Machboos",
    image: "/fish-machboos-gulf-rice-dish.jpg",
    nutritionPer100g: { calories: 145, fat: 3.8, sugar: 1, sodium: 290 },
    healthImpactAr: "خيار أفضل من اللحوم، لكنه يتأثر بالملح المستخدم",
    healthImpactEn: "Better option than meat, but affected by salt used",
    alternativeAr: "تقليل المرقة المالحة وزيادة الليمون بدل الملح",
    alternativeEn: "Reduce salty broth and increase lemon instead of salt",
    colorIndex: "green",
  },
  {
    id: 12,
    nameAr: "مجبوس دجاج",
    nameEn: "Chicken Machboos",
    image: "/chicken-machboos-gulf-rice-dish.jpg",
    nutritionPer100g: { calories: 165, fat: 5.5, sugar: 1.2, sodium: 240 },
    healthImpactAr: "معتدل لكنه قد يرفع السعرات بتكراره مع الرز الكثير",
    healthImpactEn: "Moderate but may raise calories with repetition and lots of rice",
    alternativeAr: "تقليل الرز وزيادة الخضار",
    alternativeEn: "Reduce rice and increase vegetables",
    colorIndex: "yellow",
  },
  {
    id: 13,
    nameAr: "مطبق لحم",
    nameEn: "Meat Mutabbaq",
    image: "/meat-mutabbaq-fried-pastry.jpg",
    nutritionPer100g: { calories: 245, fat: 12, sugar: 1.8, sodium: 380 },
    healthImpactAr: "دهون مشبعة مرتفعة مع تكرار القلي",
    healthImpactEn: "High saturated fats with repeated frying",
    alternativeAr: "مطبق مشوي بدل المقلي",
    alternativeEn: "Baked mutabbaq instead of fried",
    colorIndex: "red",
  },
  {
    id: 14,
    nameAr: "مطبق خضار",
    nameEn: "Veggie Mutabbaq",
    image: "/vegetable-mutabbaq-fried-pastry.jpg",
    nutritionPer100g: { calories: 210, fat: 8.5, sugar: 2, sodium: 300 },
    healthImpactAr: "أفضل من اللحمي لكن القلي يبقى مشكلة عند التكرار",
    healthImpactEn: "Better than meat version but frying remains an issue with repetition",
    alternativeAr: "خبزه في الفرن بدلاً من القلي",
    alternativeEn: "Bake in oven instead of frying",
    colorIndex: "yellow",
  },
  {
    id: 15,
    nameAr: "سمبوسة جبن",
    nameEn: "Cheese Sambusa",
    image: "/cheese-sambusa-fried-pastry.jpg",
    nutritionPer100g: { calories: 290, fat: 17, sugar: 1, sodium: 420 },
    healthImpactAr: "القلي + الجبن = دهون وصوديوم عاليان مع التكرار",
    healthImpactEn: "Frying + cheese = high fats and sodium with repetition",
    alternativeAr: "سمبوسة بالفرن أو بحشوة سبانخ خفيفة",
    alternativeEn: "Oven-baked sambusa or with light spinach filling",
    colorIndex: "red",
  },
  {
    id: 16,
    nameAr: "سمبوسة لحم",
    nameEn: "Meat Sambusa",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 280, fat: 15, sugar: 1, sodium: 410 },
    healthImpactAr: "نفس مخاطر المقلي — يرفع السعرات والصوديوم مع التكرار",
    healthImpactEn: "Same fried risks — raises calories and sodium with repetition",
    alternativeAr: "تحضيرها في الفرن بدل الزيت",
    alternativeEn: "Prepare in oven instead of oil",
    colorIndex: "red",
  },
  {
    id: 17,
    nameAr: "خبز تميس",
    nameEn: "Tamees Bread",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 290, fat: 2.6, sugar: 2, sodium: 520 },
    healthImpactAr: "الصوديوم المرتفع قد يرفع الضغط عند الاستهلاك اليومي",
    healthImpactEn: "High sodium may raise blood pressure with daily consumption",
    alternativeAr: "تقليل الكمية أو استبداله بخبز حبوب كاملة أقل ملحًا",
    alternativeEn: "Reduce quantity or replace with less salty whole grain bread",
    colorIndex: "yellow",
  },
  {
    id: 18,
    nameAr: "خبز رقاق",
    nameEn: "Regag Bread",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 310, fat: 3, sugar: 1.5, sodium: 450 },
    healthImpactAr: "طحين مكرر + غالباً يقدم مع دهن، يرفع الحمل السكري والحراري عند التكرار",
    healthImpactEn: "Refined flour + often served with fat, raises glycemic and caloric load with repetition",
    alternativeAr: "خبز رقاق مصنوع من حبوب كاملة أو تقليل الكمية",
    alternativeEn: "Whole grain regag or reduce quantity",
    colorIndex: "yellow",
  },
  {
    id: 19,
    nameAr: "خبز عربي",
    nameEn: "Arabic Pita",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 275, fat: 0.7, sugar: 1.5, sodium: 322 },
    healthImpactAr: "كارب مكرر قد يرفع سكر الدم مع كثرة الاستهلاك",
    healthImpactEn: "Refined carbs may raise blood sugar with excessive consumption",
    alternativeAr: "خبز عربي حبوب كاملة",
    alternativeEn: "Whole grain Arabic pita",
    colorIndex: "yellow",
  },
  {
    id: 20,
    nameAr: "حمص",
    nameEn: "Hummus",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 166, fat: 9.6, sugar: 0.3, sodium: 246 },
    healthImpactAr: "جيد للشبع والبروتين النباتي، المشكلة فقط في الإضافات الدهنية العالية",
    healthImpactEn: "Good for satiety and plant protein, only issue is high fat additions",
    alternativeAr: "حمص بطحينة أقل وزيت أقل",
    alternativeEn: "Hummus with less tahini and less oil",
    colorIndex: "green",
  },
  {
    id: 21,
    nameAr: "فلافل",
    nameEn: "Falafel",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 333, fat: 17.8, sugar: 0.5, sodium: 294 },
    healthImpactAr: "القلي المتكرر يرفع السعرات ويزيد الدهون المتراكمة",
    healthImpactEn: "Repeated frying raises calories and increases accumulated fats",
    alternativeAr: "فلافل بالفرن أو هوائي",
    alternativeEn: "Oven-baked or air-fried falafel",
    colorIndex: "yellow",
  },
  {
    id: 22,
    nameAr: "تبولة",
    nameEn: "Tabbouleh",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 120, fat: 6, sugar: 2.3, sodium: 180 },
    healthImpactAr: "خيار خفيف ومساعد في التحكم بالشهية",
    healthImpactEn: "Light option that helps control appetite",
    alternativeAr: "لا حاجة — بالفعل بديل صحي",
    alternativeEn: "No need — already a healthy option",
    colorIndex: "green",
  },
  {
    id: 23,
    nameAr: "سلطة فتوش",
    nameEn: "Fattoush",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 110, fat: 5, sugar: 2, sodium: 200 },
    healthImpactAr: "صحية إجمالًا لكن الخبز المقلي قد يرفع السعرات",
    healthImpactEn: "Generally healthy but fried bread may raise calories",
    alternativeAr: "استخدام رقاق مشوي بدل المقلي",
    alternativeEn: "Use toasted bread instead of fried",
    colorIndex: "green",
  },
  {
    id: 24,
    nameAr: "كبدة مشوية",
    nameEn: "Grilled Liver",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 175, fat: 6, sugar: 0, sodium: 85 },
    healthImpactAr: "مصدر جيد للحديد والبروتين، آمن عند الاعتدال",
    healthImpactEn: "Good source of iron and protein, safe in moderation",
    alternativeAr: "لا حاجة — خيار جيد بالفعل",
    alternativeEn: "No need — already a good option",
    colorIndex: "green",
  },
  {
    id: 25,
    nameAr: "كبدة بالكمون (مقلية)",
    nameEn: "Spiced Liver (pan)",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 215, fat: 11, sugar: 0, sodium: 300 },
    healthImpactAr: "القلي يضيف دهون ويزيد الحمل الحراري",
    healthImpactEn: "Frying adds fats and increases caloric load",
    alternativeAr: "شوي بدل القلي",
    alternativeEn: "Grill instead of frying",
    colorIndex: "yellow",
  },
  {
    id: 26,
    nameAr: "كباب/كفتة مشوية",
    nameEn: "Kofta Kebab",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 250, fat: 14, sugar: 0, sodium: 420 },
    healthImpactAr: "اللحوم المشوية أفضل من المقلية، لكن الصوديوم قد يكون مرتفع",
    healthImpactEn: "Grilled meats better than fried, but sodium may be high",
    alternativeAr: "استخدام لحم قليل الدهن وتقليل الملح",
    alternativeEn: "Use lean meat and reduce salt",
    colorIndex: "yellow",
  },
  {
    id: 27,
    nameAr: "هامور مشوي",
    nameEn: "Grilled Hamour",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 140, fat: 3.5, sugar: 0, sodium: 170 },
    healthImpactAr: "بروتين خفيف وصحي للقلب",
    healthImpactEn: "Light protein and heart-healthy",
    alternativeAr: "لا حاجة — خيار ممتاز",
    alternativeEn: "No need — excellent option",
    colorIndex: "green",
  },
  {
    id: 28,
    nameAr: "دجاج على الفحم",
    nameEn: "Charcoal Chicken",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 165, fat: 6, sugar: 0, sodium: 210 },
    healthImpactAr: "صحي إذا نُزع الجلد وقلّ الملح",
    healthImpactEn: "Healthy if skin removed and salt reduced",
    alternativeAr: "إضافة سلطة بدل الخبز",
    alternativeEn: "Add salad instead of bread",
    colorIndex: "green",
  },
  {
    id: 29,
    nameAr: "شاورما دجاج",
    nameEn: "Chicken Shawarma",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 420, fat: 17, sugar: 5, sodium: 900 },
    healthImpactAr: "صوديوم مرتفع وزيوت مضافة قد ترفع الضغط والدهون",
    healthImpactEn: "High sodium and added oils may raise blood pressure and fats",
    alternativeAr: "شاورما مشوية بصلصة خفيفة",
    alternativeEn: "Grilled shawarma with light sauce",
    colorIndex: "red",
  },
  {
    id: 30,
    nameAr: "شاورما لحم",
    nameEn: "Beef Shawarma",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 470, fat: 22, sugar: 5, sodium: 950 },
    healthImpactAr: "أعلى دهون وصوديوم من الدجاج، خطر أعلى عند التكرار",
    healthImpactEn: "Higher fats and sodium than chicken, higher risk with repetition",
    alternativeAr: "استبدالها بدجاج مشوي",
    alternativeEn: "Replace with grilled chicken",
    colorIndex: "red",
  },
  {
    id: 31,
    nameAr: "أرز بسمتي أبيض مطبوخ",
    nameEn: "Cooked Basmati Rice",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 130, fat: 0.3, sugar: 0.1, sodium: 1 },
    healthImpactAr: "آمن لكن يرفع السعرات إن تكرر بكميات كبيرة",
    healthImpactEn: "Safe but raises calories if repeated in large quantities",
    alternativeAr: "نصف رز ونصف خضار",
    alternativeEn: "Half rice and half vegetables",
    colorIndex: "green",
  },
  {
    id: 32,
    nameAr: "عدس مطبوخ",
    nameEn: "Cooked Lentils",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 116, fat: 0.4, sugar: 1, sodium: 4 },
    healthImpactAr: "غني بالألياف والبروتين النباتي، خيار ممتاز",
    healthImpactEn: "Rich in fiber and plant protein, excellent option",
    alternativeAr: "—",
    alternativeEn: "—",
    colorIndex: "green",
  },
  {
    id: 33,
    nameAr: "فول مدمس",
    nameEn: "Ful Medames",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 110, fat: 0.5, sugar: 0.6, sodium: 30 },
    healthImpactAr: "مشبع ومفيد للتحكم بالجوع",
    healthImpactEn: "Filling and helpful for hunger control",
    alternativeAr: "—",
    alternativeEn: "—",
    colorIndex: "green",
  },
  {
    id: 34,
    nameAr: "لبنة",
    nameEn: "Labneh",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 170, fat: 10, sugar: 4, sodium: 250 },
    healthImpactAr: "دهون مشبعة قد تتراكم مع الإفراط",
    healthImpactEn: "Saturated fats may accumulate with excess",
    alternativeAr: "لبنة قليلة الدسم",
    alternativeEn: "Low-fat labneh",
    colorIndex: "yellow",
  },
  {
    id: 35,
    nameAr: "زبادي سادة",
    nameEn: "Plain Yogurt",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 60, fat: 3.8, sugar: 4.7, sodium: 36 },
    healthImpactAr: "خيار خفيف يدعم الهضم ويعتبر مناسباً للسعرات اليومية",
    healthImpactEn: "Light option that supports digestion and suitable for daily calories",
    alternativeAr: "—",
    alternativeEn: "—",
    colorIndex: "green",
  },
  {
    id: 36,
    nameAr: "لبن/عيران",
    nameEn: "Laban / Ayran",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 40, fat: 1.5, sugar: 3.5, sodium: 150 },
    healthImpactAr: "جيد للترطيب، فقط راقب الصوديوم في الأنواع التجارية",
    healthImpactEn: "Good for hydration, just watch sodium in commercial types",
    alternativeAr: "تقليل الملح في التحضير المنزلي",
    alternativeEn: "Reduce salt in homemade preparation",
    colorIndex: "green",
  },
  {
    id: 37,
    nameAr: "قهوة عربية",
    nameEn: "Arabic Coffee",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 0, fat: 0, sugar: 0, sodium: 0 },
    healthImpactAr: "آمنة بحد معقول، الخطر يأتي غالباً من التمر المرافق لها",
    healthImpactEn: "Safe in moderation, risk usually comes from accompanying dates",
    alternativeAr: "—",
    alternativeEn: "—",
    colorIndex: "green",
  },
  {
    id: 38,
    nameAr: "شاي كرك بسكر",
    nameEn: "Karak Tea (with sugar)",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 65, fat: 2.5, sugar: 9, sodium: 40 },
    healthImpactAr: "السكر المتكرر قد يرفع سكر الدم والوزن مع الوقت",
    healthImpactEn: "Repeated sugar may raise blood sugar and weight over time",
    alternativeAr: "كرك مخفف السكر أو بدون سكر",
    alternativeEn: "Reduced sugar or sugar-free karak",
    colorIndex: "yellow",
  },
  {
    id: 39,
    nameAr: "تمر خلاص",
    nameEn: "Khalas Dates",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 277, fat: 0.2, sugar: 66, sodium: 1 },
    healthImpactAr: "حمل سكري مرتفع يرفع مقاومة الإنسولين مع التكرار",
    healthImpactEn: "High glycemic load raises insulin resistance with repetition",
    alternativeAr: "2–3 تمرات بدلاً من حفنة كاملة",
    alternativeEn: "2–3 dates instead of a full handful",
    colorIndex: "red",
  },
  {
    id: 40,
    nameAr: "تمر سكري",
    nameEn: "Sukkari Dates",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 300, fat: 0.5, sugar: 72, sodium: 2 },
    healthImpactAr: "سكريات أعلى من معظم الأنواع، ترفع دهون الأحشاء عند الإكثار",
    healthImpactEn: "Higher sugars than most types, raises visceral fat with excess",
    alternativeAr: "تقليل الكمية أو اختيار تمر أقل حلاوة",
    alternativeEn: "Reduce quantity or choose less sweet dates",
    colorIndex: "red",
  },
  {
    id: 41,
    nameAr: "معصوب",
    nameEn: "Masoub",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 210, fat: 6, sugar: 20, sodium: 120 },
    healthImpactAr: "السكر المضاف والموز قد يرفعان السعرات والسكر مع التكرار",
    healthImpactEn: "Added sugar and banana may raise calories and sugar with repetition",
    alternativeAr: "معصوب بدون عسل أو مع سكر أقل",
    alternativeEn: "Masoub without honey or with less sugar",
    colorIndex: "yellow",
  },
  {
    id: 42,
    nameAr: "عريكة",
    nameEn: "Areeka",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 230, fat: 8, sugar: 19, sodium: 110 },
    healthImpactAr: "حمل سكري عالي عند تكرار تناوله",
    healthImpactEn: "High glycemic load with repeated consumption",
    alternativeAr: "تقليل العسل أو استبداله بالتمر فقط",
    alternativeEn: "Reduce honey or replace with dates only",
    colorIndex: "yellow",
  },
  {
    id: 43,
    nameAr: "لقيمات",
    nameEn: "Luqaimat",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 330, fat: 14, sugar: 23, sodium: 270 },
    healthImpactAr: "تجمع بين المقلي والسكريات — خطورة عالية مع التكرار",
    healthImpactEn: "Combines fried and sugars — high risk with repetition",
    alternativeAr: "خبزها في الفرن واستخدام دبس أخف",
    alternativeEn: "Bake in oven and use lighter syrup",
    colorIndex: "red",
  },
  {
    id: 44,
    nameAr: "كنافة",
    nameEn: "Kunafa",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 420, fat: 20, sugar: 37, sodium: 320 },
    healthImpactAr: "دهون مشبعة وسكر عالي — تزيد الوزن سريعًا مع التكرار",
    healthImpactEn: "Saturated fats and high sugar — increases weight quickly with repetition",
    alternativeAr: "كنافة بدون قطر أو سكر أقل",
    alternativeEn: "Kunafa without syrup or less sugar",
    colorIndex: "red",
  },
  {
    id: 45,
    nameAr: "بسبوسة",
    nameEn: "Basbousa",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 370, fat: 17, sugar: 28, sodium: 260 },
    healthImpactAr: "سكر ودهن معًا — يزيد العبء الحراري مع الوقت",
    healthImpactEn: "Sugar and fat together — increases caloric burden over time",
    alternativeAr: "بسبوسة بدقيق شوفان وتقليل القطر",
    alternativeEn: "Basbousa with oat flour and reduced syrup",
    colorIndex: "red",
  },
  {
    id: 46,
    nameAr: "مهلبية",
    nameEn: "Muhallabia",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 130, fat: 3, sugar: 16, sodium: 50 },
    healthImpactAr: "سكر متوسط — مقبولة إن لم تتكرر يومياً",
    healthImpactEn: "Moderate sugar — acceptable if not repeated daily",
    alternativeAr: "تحضيرها بسكر أقل أو محليات طبيعية",
    alternativeEn: "Prepare with less sugar or natural sweeteners",
    colorIndex: "yellow",
  },
  {
    id: 47,
    nameAr: "عصير مانجو",
    nameEn: "Mango Juice",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 60, fat: 0.2, sugar: 14, sodium: 5 },
    healthImpactAr: "السكر السريع من العصائر يرفع سكر الدم مقارنة بتناول الفاكهة",
    healthImpactEn: "Fast sugar from juices raises blood sugar compared to eating fruit",
    alternativeAr: "أكل المانجو كاملة بدل العصير",
    alternativeEn: "Eat whole mango instead of juice",
    colorIndex: "yellow",
  },
  {
    id: 48,
    nameAr: "عصير رمان",
    nameEn: "Pomegranate Juice",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 54, fat: 0.3, sugar: 13, sodium: 1 },
    healthImpactAr: "مفيد كمضاد أكسدة لكن سكر العصير يبقى مرتفع نسبيًا",
    healthImpactEn: "Beneficial as antioxidant but juice sugar remains relatively high",
    alternativeAr: "تناول بذور الرمان بدل العصير",
    alternativeEn: "Eat pomegranate seeds instead of juice",
    colorIndex: "yellow",
  },
  {
    id: 49,
    nameAr: "ماء",
    nameEn: "Water",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 0, fat: 0, sugar: 0, sodium: 0 },
    healthImpactAr: "الأفضل على الإطلاق للترطيب اليومي",
    healthImpactEn: "The absolute best for daily hydration",
    alternativeAr: "—",
    alternativeEn: "—",
    colorIndex: "green",
  },
  {
    id: 50,
    nameAr: "لبنة قليلة الملح",
    nameEn: "Low-salt Labneh",
    image: "/placeholder.svg?height=400&width=400",
    nutritionPer100g: { calories: 150, fat: 8, sugar: 3, sodium: 120 },
    healthImpactAr: "خيار أخف من اللبنة العادية — جيد للاستخدام المتكرر",
    healthImpactEn: "Lighter option than regular labneh — good for repeated use",
    alternativeAr: "—",
    alternativeEn: "—",
    colorIndex: "green",
  },
]
